### ISSUE TITLE
BIF development

### ISSUE THREAD

**Issue by danielgoodwin** [rpgleparser/rpgleparser#16]
Issue covering 
- development of BIF additions to grammar
- test cases for BIF functions
- tag for code changes

Reference http://publib.boulder.ibm.com/iseries/v5r2/ic2924/books/c092508302.htm#ToC_706

**Comment by danielgoodwin** [comment]
Q: Cant write permission be granted to my account to upload changes (on its own branch)?
I get error.. Permission to rpgleparser/rpgleparser.git denied to danielgoodwin , though (of course) it could be an issue on my end as well.

**Comment by ryaneberly** [comment]
Nice work.  Looks great.
Having gone that far, we might as well name the parameters appropriately.

For example:
bif_check: BIF_CHECK OPEN_PAREN comparator=expression COLON base=expression (COLON start=expression)? CLOSE_PAREN;

Then the consumer can refer to each parameter by name, instead of position.

**Comment by danielgoodwin** [comment]
I'd agree, Working on a basic program flow for the free2fixed, so when I have that I will e revisiting the finishing of test cases for all BIFS and will add in named arguments.

**Comment by danielgoodwin** [comment]
Named arguments (where possible) added for BIF functions
I've also merged that part of branch in - dont want it getting too out of sync.

**Comment by ryaneberly** [comment]
Great. Thanks, I agree w/ staying in sync.  Thanks for contributing.

**Comment by ryaneberly** [comment]
thanks for doing these, daniel.
