### ISSUE TITLE
Procedure name using opcode

### ISSUE THREAD

**Issue by danielgoodwin** [rpgleparser/rpgleparser#21]
Im now testing against 'real' programs, checking that parsing OK.
I've came across this one where code is a wrapper for socket functionality, so declared functions actually clash with op codes (open/close..)
As far as I can tell, code is then aligning itself with the opcode and not the function - seems sensible, so with my limited experience, do I need a symbol table or something to align parser with the internal function AS WELL AS the opcode. In the case below I can obviously create a rule for the identifier, but the definition of the close procedure could be anything.

```
      *.. 1 ...+... 2 ...+... 3 ...+... 4 ...+... 5 ...+... 6 ...+... 7 ...+... 8 ...+... 9 ...+... 10
     D*ame+++++++++++ETDsFrom+++To/L+++IDc.Keywords+++++++++++++++++++++++++++++Comments++++++++++++
     D close           PR            10I 0 ExtProc('close')
     D  filehandle                   10I 0 Value
      *
     D open            PR            10I 0 ExtProc('open')
     D  filename                       *   Value
     D  openflags                    10I 0 Value
     D  mode                         10U 0 Value options(*nopass)
     D  codepage                     10U 0 Value options(*nopass)
      *
     D Err_Flag        S             10I 0

      /free
       // Close IFS file
       RC = Close(Err_Flag);
       If RC = -1;

          Exsr *Pssr;

       EndIf;
      
      /end-free
 ```

**Comment by ryaneberly** [comment]
Oh boy,you found quite the scenario.
  An OpCode immediately followed by a Left paren is Lexed as a Operation Extender.  It would be awkward and error-prone to reinterpret that in the Parser.

  Your suggestion of a symbol table seems to be spot on.  You are venturing into an area I have zero Antlr experience in.  Sadly this means we won't have an actionless grammar anymore.  :-)

Check out the Tokens Section (keywords) on 
https://theantlrguy.atlassian.net/wiki/display/ANTLR4/Grammar+Structure
and the related section in the Antlr book if you have it. 

Basically,
* Add a HashMap to @lexer::members to store the procedure names.
* Add the name of the PR to the hashmap as it is processed by the lexer.
* Make sure Close matches OP_CLOSE only if there is no "Close" in the hashmap.   (otherwise it will trickle down and match ID, and the parser will treat it as a function call).  applies to all op codes.

Caveat:
The symbol lookup in the hashmap needs to be case-insensitive.  Suggest using https://commons.apache.org/proper/commons-collections/javadocs/api-3.2.1/org/apache/commons/collections/map/CaseInsensitiveMap.html
Though you could toUppercase() the store/lookup.

Want to give it a shot?

**Comment by TheEricWilson** [comment]
Oh and it is usually better to lowercase things as some accented characters loose their accents upon being uppercased. I frequently forget this fact too

**Comment by TheEricWilson** [comment]
Can we not handle the operational extenders as a set of valid ones by op ode?

It seems like the collision of these tokens would be able to be handled without needing a symbol table just yet

close() would be a function call whereas close(e) would be the opcode

The likelihood that someone would name the arguments to be exactly what the set of valid extenders are should be pretty small . Unless someone was just being malicious:-)

**Comment by ryaneberly** [comment]
Ok, I had to try compiling it a bit....

The following
Close(Err_Flag); // is a compilation error because the compiler thinks its
an opcode

So. the rule is.... it's only an opcode if its the first non-whitespace
after column 7?

**Comment by TheEricWilson** [comment]
Yes an opcode can only appear once in a statement with eval being an implied one…

**Comment by ryaneberly** [comment]
Ok, after some thinking... 

I recommend move the OP_xxxxx (lexer lines 91-152) to their own mode. mode(opCodes).

The opCodes mode matches all opCodes 
AND 
The ID from the FREE mode.
(skips whitespace)

On all of these it drops to either the FreeOpExtender or FREE modes.

This means that the OP_xxxxx code can only be the first significant token in the line and nowhere else.  As it should be.

**Comment by ryaneberly** [comment]
@danielgoodwin , I checked in proof of concept for the first few op codes.  including commit and close.  You can try your example now.

**Comment by ryaneberly** [comment]
finished the op codes.
