### ISSUE TITLE
RPGLE Scripting language parser

### ISSUE THREAD

**Issue by UdayaBhanuG** [rpgleparser/rpgleparser#22]
Is there a way to parse AS400 service programs aka scripts? This program only parses RPGLE sources, AFAIK.

**Comment by ryaneberly** [comment]
Are you talking about CL and CLLE sources?

**Comment by UdayaBhanuG** [comment]
yes. I am talking about the scripts, yes, the CL sources.

**Comment by ryaneberly** [comment]
That would be an interesting exercise.   The CL syntax is much less complicated than RPG :-)

**Comment by TheEricWilson** [comment]
CL & CLLE are entirely different beasts from RPGLE. Other than parsing Declarations and flow control it would be difficult since one can make their own commands *CMD objects. This precludes doing things before the fact. Depending on what you are trying to accomplish there may be other ways using the existing iSeries APIs to accomplish the task. But you are right that this project only deals with RPG sources.

**Comment by ryaneberly** [comment]
the RPGLE parser has a lot of *semantic* meaning built it.  Such as the implementation of all the BIFs.  I think a purely syntactic (structure) approach to CLLE would be comparative simple to what we've done.

@UdayaBhanuG , but as Eric says, you can get a lot of info from the system about the compiled service program (files it accesses, programs it calls).  DSPPGMREF's output can even be streamed to a physical file and queried via SQL.
