### ISSUE TITLE
'+' in built in function arguments

### ISSUE THREAD

**Issue by danielgoodwin** [rpgleparser/rpgleparser#31]
While not a requirement, the use of + as last token on line in a list of built in functions is allowable. Rather then changing each BIF, Im hoping there is a simpler way of dealing with it where PLUS + NEWLINE is skipped in BIF args.

/continuations/bif_args_continuations.rpgle added as example.

```
     C                   If        SP > 0
     C                   Eval      DataValue = %Replace('&amp;' : DataValue: +
     C                                          %Scan('[' : DataValue): 1)
     C                   EndIf


```

**Comment by ryaneberly** [comment]
Gotta love language ambiguities :)

**Comment by DavidGregory084** [comment]
Hi both, you may be interested to know that thanks to my colleague James Talbot I now know that this is not actually a language ambiguity. That is actually interpreted by the compiler as a unary `+` because the BIF is `%scan`, which returns a numeric value - this might not make it any easier to implement but at least it's not a continuation character. :)

**Comment by ryaneberly** [comment]
Hey David,  
    Thanks!  That is actually a LOT easier to implement.

**Comment by ryaneberly** [comment]
implemented
