### ISSUE TITLE
What will this be used for?

### ISSUE THREAD

**Issue by WorksOfBarry** [rpgleparser/rpgleparser#6]
RPGLE developer here, I think this is quite awesome.. but I have no idea what you would use this for.

Could you give me some examples?

**Comment by TheEricWilson** [comment]
I have a number of uses planned…
Inferring Foreign Key relationships based on KLISTs and SETLL and READE (Good candidate for a One to Many), KLIST and CHAIN (Possible One to One)
Conversion of fixed format to free format
Impact analysis
and a number of others.

**Comment by WorksOfBarry** [comment]
Sounds good..

"Conversion of fixed format to free format" is probably going to be a very big one. I was trained in free-format completely and the fixed format is a pain to read - but I can just about get through it.

I've been watching the project.. I would contribute but my Java skills aren't perfect I'm afraid..

**Comment by DavidGregory084** [comment]
Hi Liam,
  There are a lot of things this can be used for; Eric has mentioned a number of them. To expand on those a bit:
* Static analysis - if you can build a tree-like representation of code the way an ANTLR parser does you efficiently encode the context of every definition and expression. This means that you can ask questions like "are there any global variables which are only used in a single subprocedure" by simply checking whether there is something that the parser recognises as a local variable definition which is only referenced in one subprocedure's subtree.
* Conversion - this could be achieved by using ANTLR's generated Listeners, which use a built-in tree walker to trigger method calls when each rule recognised by the parser is entered or exited. You can implement as many or as few of these methods as you want, and this would allow you to emit a corresponding free-format definition to a file whenever a fixed-format definition is exited while leaving free-format definitions unchanged, for example. Note that this isn't restricted to any particular manipulation task; you could just as easily use it for applying code style rules, auto-indenting or converting redundant code into simpler forms.
* Language tools - one of the interesting things about this project is the possibility of incorporating the resulting parser into an IDE plugin so that we don't have to use RDP or RDi or whatever it's called right now (which is awful to use and buggy as hell).

**Comment by WorksOfBarry** [comment]
From what you have described, static analysis sounds like it would be very handy for source documentation. You mention "auto-indenting" which sounds brilliant already. This would be handy for RDi (Rational Developer for i / technically it's just eclipse with a bunch of plugins written by IBM) - as you've said it's buggy as hell and considering I have to use it for my day job I can confirm it's terrible.

You're making me fall in love with this project. Coming from a C# and PHP background I'm sure I can take a look through some of the Java source and maybe help out (if even needed) (I do have some Java skill, I have to write some of my companies web-services within Java which interacts with RPG programs).

Keep up the good work, I'll be spreading the word about this.

**Comment by DavidGregory084** [comment]
It's worth pointing out though: at the moment this is just a parser. It doesn't do anything else but build a data structure to represent the code - all of those things I mentioned are possibilities but all are effectively projects on their own.

**Comment by WorksOfBarry** [comment]
Honestly it's a good start.

I've been considering posting my RPGLE source documentation tool (which also a basic parser) which is written in PHP but I don't feel the need to now.

This might not seem like help to you, but I will get on GitHub's case about adding syntax highlighting for the RPGLE language ASAP though - I'd really love to see more Open Source RPG stuff.

**Comment by ryaneberly** [comment]
I would add to the possibilities list:
   * a REPL <http://www.javarepl.com/console.html>
which is probably a bit ludicrous, :-).

However, I think easy applications would be static analysis,
micro/incremental code transformations, and something like the
documentation tool Liam mentions.

Liam,
   What kind of doc output are you generating?

If you are interested in contributing, the parse tree is still a bit rough
(right, Eric?).  Even just feedback, and sample tests would be helpful.  It
needs some semantic fleshing out, structurally it seems to handle most
RPGLE code.

**Comment by WorksOfBarry** [comment]
It just generates ugly HTML, the only reason I created it is because I haven't been able to find a successful documenting tool that works for the language.

I'll run some tests over code that I have then, and see what your program comes up with when I get some free time. I'm actually at work at the moment so I'll get around to it during my weekend.

**Comment by DavidGregory084** [comment]
There are two documentation tools as far as I know:
http://sourceforge.net/projects/rpgdoc/
http://iledocs.sourceforge.net/
I'm not sure if either of them are any good, though!

**Comment by WorksOfBarry** [comment]
I opened sourced mine yesterday, you can find it by viewing my account. I'll probably take it down in about a weeks time.

**Comment by TheEricWilson** [comment]
Things are looking really good right now. All tests are passing and all the RPG code that I have thrown at it so far works. I am going to try to do a fixed format to free format converter based on this now to see how close we are. If I get something working, should I include it in the distribution as an example???

**Comment by WorksOfBarry** [comment]
"should I include it in the distribution as an example"

Yes! I would suggest pushing out as much as possible, people love examples - it may even take off if it turns out to be handy.

**Comment by ryaneberly** [comment]
Sure thing.  Eric.  Thanks for your efforts

**Comment by ryaneberly** [comment]
Are we ready to push whats in the 'rename' branch into the master branch,
then?

**Comment by TheEricWilson** [comment]
I say sure and do cleaning tomorrow if needed

**Comment by WorksOfBarry** [comment]
Do you guys have some kind of discussion group?

I'd like to talk to you guys about something private I'd like to work on, but I'd like to involve you guys with it.

**Comment by TheEricWilson** [comment]
I am not aware of one. I think that would be a good idea though.

**Comment by WorksOfBarry** [comment]
I wish I could email you privately.

Hit me up ASAP, when I've seen an email from you I'll remove this comment.
mrliamallan@live.co.uk

**Comment by ryaneberly** [comment]
https://gitter.im/rpgleparser/rpgleparser
